server:
  port: 9000
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productservice
          uri: http://localhost:9001
          predicates:
#            - Path=/api/v1/productItem/**
            - Path=/api/v1/product/**
          filters:
            - AuthFilter
        - id: employeeservice
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - AuthFilter
        - id: hairservice
          uri: http://localhost:9004
          predicates:
            - Path=/api/v1/service/**
          filters:
            - AuthFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"

