server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: productservice
          uri: lb://productservice
          predicates:
            - Path=/api/v1/productItem/**
#          filters:
#            - AuthFilter
        - id: productservice-manager
          uri: lb://productservice
          predicates:
            - Path=/api/v1/management/**
#          filters:
#            - AuthFilter
        - id: appointmentservice
          uri: lb://appointmentservice
          predicates:
            - Path=/api/v1/appointment/**
#          filters:
#            - AuthFilter
        - id: hairservice
          uri: lb://hairservice
          predicates:
            - Path=/api/v1/hairservice/**
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/api/v1/order/**
        - id: orderservice-cart
          uri: lb://orderservice
          predicates:
            - Path=/api/v1/cart/**
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/v1/auth/**
        - id: userservice-user
          uri: lb://userservice
          predicates:
            - Path=/api/v1/user/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
